######################################################################
# Automatically generated by qmake (2.01a) Sun Jun 23 16:25:34 2013
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += FileUtils.hpp \
           Peptide.hpp \
           Predicate.hpp \
           ProgressCount.hpp \
           SpectraST_base64.h \
           SpectraST_constants.h \
           SpectraST_cramp.hpp \
           SpectraST_kwset.h \
           SpectraST_obstack.h \
           SpectraST_ramp.h \
           SpectraST_util.h \
           SpectraSTCandidate.hpp \
           SpectraSTConstants.hpp \
           SpectraSTCreateParams.hpp \
           SpectraSTDenoiser.hpp \
           SpectraSTDtaSearchTask.hpp \
           SpectraSTFastaFileHandler.hpp \
           SpectraSTFileList.hpp \
           SpectraSTHtmlSearchOutput.hpp \
           SpectraSTLib.hpp \
           SpectraSTLibEntry.hpp \
           SpectraSTLibImporter.hpp \
           SpectraSTLibIndex.hpp \
           SpectraSTLog.hpp \
           SpectraSTMgfSearchTask.hpp \
           SpectraSTMs2LibImporter.hpp \
           SpectraSTMspLibImporter.hpp \
           SpectraSTMspSearchTask.hpp \
           SpectraSTMzLibIndex.hpp \
           SpectraSTMzXMLLibImporter.hpp \
           SpectraSTMzXMLSearchTask.hpp \
           SpectraSTPeakList.hpp \
           SpectraSTPeptideLibIndex.hpp \
           SpectraSTPepXMLLibImporter.hpp \
           SpectraSTPepXMLSearchOutput.hpp \
           SpectraSTQuery.hpp \
           SpectraSTReplicates.hpp \
           SpectraSTSearch.hpp \
           SpectraSTSearchOutput.hpp \
           SpectraSTSearchParams.hpp \
           SpectraSTSearchTask.hpp \
           SpectraSTSearchTaskStats.hpp \
           SpectraSTSimScores.hpp \
           SpectraSTSpLibImporter.hpp \
           SpectraSTTsvLibImporter.hpp \
           SpectraSTTxtSearchOutput.hpp \
           SpectraSTXHunterLibImporter.hpp \
           SpectraSTXlsSearchOutput.hpp \
           XMLWalker.hpp \
           sqlite3.h
SOURCES += FileUtils.cpp \
           Peptide.cpp \
           Predicate.cpp \
           ProgressCount.cpp \
           SpectraST_base64.cpp \
           SpectraST_cramp.cpp \
           SpectraST_kwset.cpp \
           SpectraST_obstack.cpp \
           SpectraST_ramp.cpp \
           SpectraST_util.cpp \
           SpectraSTCandidate.cpp \
           SpectraSTCreateParams.cpp \
           SpectraSTDenoiser.cpp \
           SpectraSTDtaSearchTask.cpp \
           SpectraSTFastaFileHandler.cpp \
           SpectraSTFileList.cpp \
           SpectraSTHtmlSearchOutput.cpp \
           SpectraSTLib.cpp \
           SpectraSTLibEntry.cpp \
           SpectraSTLibImporter.cpp \
           SpectraSTLibIndex.cpp \
           SpectraSTLog.cpp \
           SpectraSTMain.cpp \
           SpectraSTMgfSearchTask.cpp \
           SpectraSTMs2LibImporter.cpp \
           SpectraSTMspLibImporter.cpp \
           SpectraSTMspSearchTask.cpp \
           SpectraSTMzLibIndex.cpp \
           SpectraSTMzXMLLibImporter.cpp \
           SpectraSTMzXMLSearchTask.cpp \
           SpectraSTPeakList.cpp \
           SpectraSTPeptideLibIndex.cpp \
           SpectraSTPepXMLLibImporter.cpp \
           SpectraSTPepXMLSearchOutput.cpp \
           SpectraSTQuery.cpp \
           SpectraSTReplicates.cpp \
           SpectraSTSearch.cpp \
           SpectraSTSearchOutput.cpp \
           SpectraSTSearchParams.cpp \
           SpectraSTSearchTask.cpp \
           SpectraSTSearchTaskStats.cpp \
           SpectraSTSimScores.cpp \
           SpectraSTSpLibImporter.cpp \
           SpectraSTTsvLibImporter.cpp \
           SpectraSTTxtSearchOutput.cpp \
           SpectraSTXHunterLibImporter.cpp \
           SpectraSTXlsSearchOutput.cpp \
           XMLWalker.cpp \
           sqlite3.c

OTHER_FILES += \
    Makefile
